version: '3.8'

services:
  user_service:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ..:/user_service
